server:
  port: ${PORT:9081}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/${DB:erlangshen}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ${DB_USER:root}
    password: ${DB_PWD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: ${DRUID_PWD:123456}
      filter:
        slf4j:
          enabled: true
          statement-log-enabled: false
          connection-log-enabled: false
          result-set-log-enabled: true
          statement-executable-sql-log-enable: true