server:
  port: ${PORT:9081}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:bj-cynosdbmysql-grp-nofij3ug.sql.tencentcdb.com}:26223/${DB:pighand_user}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ${DB_USER:root}
    password: ${DB_PWD:Tx_qL@130#}
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: ${DRUID_PWD:123456}
      filter:
        slf4j:
          enabled: true
          statement-log-enabled: false
          connection-log-enabled: false
          result-set-log-enabled: true
          statement-executable-sql-log-enable: true
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-active: 20
          max-wait: 0
          max-idle: 5
          min-idle: 1
#      timeout: 100000